# Image parameters like width and height
image_param : {
  width   : 640,
  height  : 480
}

# Two lines of search are, top is 0.75% of height 
# and bottom is greater 
search_area : {
  top     : 240,
  bottom  : 500,
}

# Defines line
line_tolerance : {
  centerTolerance: 40,
  centerX: 320,
  centerY: 480
}